# This is a basic workflow to help you get started with Actions

name: Flake8 validation

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master, feature/* ]
  pull_request:
    branches: [ master, feature/* ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Exec flake8
      - name: Lint flake8
        run: |
          pip install flake8
          echo test, and deploy your project.
          # stop the build if there are Python syntax errors or undefined names
          git diff HEAD^ HEAD | flake8 --diff  --count  --show-source --statistics --config=.flake8
